<?php

declare(strict_types=1);

namespace AffordableMobiles\GServerlessSupportLaravel\Integration\Socialite;

use Google\Auth\Credentials\GceCredentials;
use GuzzleHttp\RequestOptions;
use Laravel\Socialite\Two\AbstractProvider;
use Laravel\Socialite\Two\ProviderInterface;
use Laravel\Socialite\Two\User;

/**
 * EntraFederatedProvider for Laravel Socialite.
 *
 * This provider enables authentication against Microsoft Entra ID (Azure AD)
 * using a secretless, federated credential flow. It is designed for applications
 * running on Google Cloud Platform (GCP) services like GCE, GKE, or Cloud Run.
 *
 * ---
 *
 * ### How It Works
 * Instead of a traditional client secret, this provider uses a short-lived OIDC token
 * generated by the GCP metadata server. This token is sent to Entra ID as a
 * `client_assertion`, proving the application's identity. This is known as
 * Workload Identity Federation.
 *
 * ---
 *
 * ### Entra ID Configuration
 * 1.  Create an **App Registration** in Entra ID.
 * 2.  Under **Authentication**, add your application's redirect URIs (e.g., `https://app.com/auth/callback`).
 * 3.  Under **Certificates & secrets** > **Federated credentials**, create a new credential with:
 * - **Scenario**: "Other issuer"
 * - **Issuer**: `https://accounts.google.com`
 * - **Subject identifier**: The numeric "Unique ID" of your GCP service account.
 * - **Audience**: `api://AzureADTokenExchange`
 */
class EntraFederatedProvider extends AbstractProvider implements ProviderInterface
{
    /**
     * The audience required by Microsoft Entra ID for the federated credential.
     */
    private const MICROSOFT_ENTRA_AUDIENCE = 'api://AzureADTokenExchange';

    /**
     * The base Azure Graph URL.
     */
    private const GRAPH_URL = 'https://graph.microsoft.com/v1.0/me';

    /**
     * The base Microsoft login URL.
     */
    private const LOGIN_URL = 'https://login.microsoftonline.com';

    /**
     * The scopes being requested.
     */
    protected $scopes = ['User.Read'];

    /**
     * The separating character for the requested scopes.
     */
    protected $scopeSeparator = ' ';

    /**
     * The tenant ID for the Azure Directory.
     *
     * @var string
     */
    protected $tenant;

    /**
     * Set the tenant ID for the request.
     *
     * @return $this
     */
    public function setTenant(string $tenant)
    {
        $this->tenant = $tenant;

        return $this;
    }

    /**
     * Get the authentication URL for the provider.
     *
     * @param string $state
     *
     * @return string
     */
    protected function getAuthUrl($state)
    {
        return $this->buildAuthUrlFromBase($this->getBaseUrl().'/oauth2/v2.0/authorize', $state);
    }

    /**
     * Get the token URL for the provider.
     *
     * @return string
     */
    protected function getTokenUrl()
    {
        return $this->getBaseUrl().'/oauth2/v2.0/token';
    }

    /**
     * Get the raw user for the given access token.
     *
     * @param string $token
     *
     * @return array
     */
    protected function getUserByToken($token)
    {
        $response = $this->getHttpClient()->get(self::GRAPH_URL, [
            RequestOptions::HEADERS => [
                'Authorization' => 'Bearer '.$token,
            ],
        ]);

        return json_decode((string) $response->getBody(), true);
    }

    /**
     * Map the raw user array to a Socialite User instance.
     *
     * @return User
     */
    protected function mapUserToObject(array $user)
    {
        return (new User())->setRaw($user)->map([
            'id'       => $user['id'],
            'nickname' => null,
            'name'     => $user['displayName'],
            'email'    => $user['userPrincipalName'],
            'avatar'   => null,
        ]);
    }

    /**
     * Get the POST fields for the token request.
     *
     * @param string $code
     *
     * @return array
     */
    protected function getTokenFields($code)
    {
        $fields = [
            'grant_type'            => 'authorization_code',
            'client_id'             => $this->clientId,
            'client_assertion_type' => 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer',
            'client_assertion'      => $this->getClientAssertion(),
            'code'                  => $code,
            'redirect_uri'          => $this->redirectUrl, // Uses the configured redirect URL
        ];

        if ($this->usesPKCE()) {
            $fields['code_verifier'] = $this->request->session()->pull('code_verifier');
        }

        return array_merge($fields, $this->parameters);
    }

    /**
     * Get the client assertion for the token request.
     *
     * This method fetches an OIDC token from the GCP metadata server
     * with the correct audience for Microsoft Entra ID.
     *
     * @return string
     */
    protected function getClientAssertion()
    {
        // Instantiate GceCredentials with the target audience.
        $credentials = new GceCredentials(null, null, self::MICROSOFT_ENTRA_AUDIENCE);
        $token       = $credentials->fetchAuthToken();

        return $token['id_token'];
    }

    /**
     * Get the base URL for the provider.
     *
     * @return string
     */
    protected function getBaseUrl()
    {
        return self::LOGIN_URL.'/'.($this->tenant ?? 'common');
    }
}
