substitutions:
  _ENVIRONMENT: 'test'
  _NPM_ENVIRONMENT: 'production'
steps:
####
## Environment Variables (.env file)
####
- id: "generate-env"
  name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args: ["./cloudbuild/generate_env_${_ENVIRONMENT}.sh"]
  secretEnv:
  - 'ENV_APP_KEY'
  waitFor: ['-']
####
## Configure latest PHP builder image
####
- id: "generate-php-builder"
  name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["./cloudbuild/scripts/build_container_image.sh"]
  waitFor: ['-']
####
## composer
####
- id: "composer"
  name: "gcr.io/gae-runtimes/buildpacks/php83/run:latest-composer"
  entrypoint: "composer"
  args: ["install", "--no-dev", "--no-progress", "-o"]
  env:
  - 'HOME=/workspace'
  waitFor:
  - "generate-php-builder"
####
## npm
####
- id: "npm-install"
  name: "gcr.io/cloud-builders/npm"
  args: ["install"]
  env:
  - 'JOBS=max'
  waitFor: ['-']
- id: "npm-run"
  name: "gcr.io/cloud-builders/npm"
  args: ["run", "$_NPM_ENVIRONMENT"]
  waitFor:
  - "npm-install"
####
## Deploy!!
####
- id: "deploy"
  name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args: ["./cloudbuild/scripts/deploy.sh", "${_ENVIRONMENT}"]
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'SHORT_SHA=$SHORT_SHA'
  - 'DEPLOY_NO_PROMOTE=$_DEPLOY_NO_PROMOTE'
  waitFor:
  - "generate-env"
  - "composer"
  - "npm-run"
####
## SECRETS
####
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/LARAVEL_APP_KEY_${_ENVIRONMENT}/versions/latest
    env: ENV_APP_KEY
####
## GLOBAL OPTIONS
####
timeout: 20m